# Include all available checks by default
checks:
  - all

# Custom checks
custom_checks:
  - code: CUSTOM001
    description: "Ensure VMSS uses managed disks"
    required_types:
      - resource
    required_labels:
      - azurerm_linux_virtual_machine_scale_set
    check:
      - expr: 'property "os_disk" is present'
      - expr: 'property "os_disk".storage_account_type != ""'
    error_message: "VMSS should use managed disks with specified storage account type"
    severity: "ERROR"

# Exclude rules that might be too restrictive for this demo
exclude:
  - AZU003 # We're using password auth for demo purposes
  - AZU006 # We're allowing SSH from any source for demo purposes
